import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";

interface PasswordResetEmailProps {
  name: string;
  /** Short-lived reset link generated by Better Auth */
  resetUrl: string;
  /** How long until the link expires, shown in the email body */
  expiresInHours?: number;
  siteName?: string;
}

/** Password reset email. Link expires in 1 hour (Better Auth default). */
export function PasswordResetEmail({
  name,
  resetUrl,
  expiresInHours = 1,
  siteName = "The Blog",
}: PasswordResetEmailProps) {
  return (
    <Html lang="en">
      <Head />
      <Preview>Reset your {siteName} password</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Heading style={styles.heading}>Reset your password</Heading>

          <Text style={styles.text}>Hi {name},</Text>
          <Text style={styles.text}>
            We received a request to reset your password. Click the button below
            to choose a new one. The link expires in{" "}
            <strong>{expiresInHours} hour{expiresInHours !== 1 ? "s" : ""}</strong>.
          </Text>

          <Section style={styles.btnSection}>
            <Button href={resetUrl} style={styles.btn}>
              Reset password
            </Button>
          </Section>

          <Text style={styles.subtext}>
            Or copy and paste this URL into your browser:
            <br />
            <span style={styles.url}>{resetUrl}</span>
          </Text>

          <Hr style={styles.hr} />

          <Text style={styles.footer}>
            If you didn't request a password reset, you can safely ignore this
            email — your password won't change.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

export default PasswordResetEmail;

const styles = {
  body: {
    backgroundColor: "#f4f4f5",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "40px auto",
    padding: "32px 40px",
    maxWidth: "560px",
  },
  heading: {
    color: "#111827",
    fontSize: "24px",
    fontWeight: "700",
    margin: "0 0 24px",
  },
  text: {
    color: "#374151",
    fontSize: "16px",
    lineHeight: "1.6",
    margin: "0 0 16px",
  },
  btnSection: { textAlign: "center" as const, margin: "32px 0" },
  btn: {
    backgroundColor: "#7c3aed",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: "600",
    padding: "12px 28px",
    textDecoration: "none",
  },
  subtext: {
    color: "#6b7280",
    fontSize: "13px",
    lineHeight: "1.5",
    wordBreak: "break-all" as const,
  },
  url: { color: "#7c3aed" },
  hr: { borderColor: "#e5e7eb", margin: "24px 0" },
  footer: { color: "#6b7280", fontSize: "13px", lineHeight: "1.5" },
};
